services:
  - type: web
    name: kalvium-worklog-automation
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: worklog-data
      mountPath: /app/data
      sizeGB: 1
    autoDeploy: true
